filebeat.prospectors:
- type: log
  enabled: true
  bulk_max_size: 0
  slow_start: true
  index: generator
  paths:
    - ./logs/filename.log
  encoding: "utf-8"
  multiline:
    pattern: '^[1-2][0-9][0-9][0-9] [Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec]'
    negate: true
    match: after

output.logstash:
  hosts: ["elk_logstash_1:5000"]

#output.console:
#  pretty: true
